export const FILE_UPLOAD='FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS='FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR='FILE_UPLOAD_ERROR';
export const FILE_LOAD='FILE_LOAD';
export const FILE_LOAD_SUCCESS='FILE_LOAD_SUCCESS';
export const FILE_LOAD_ERROR='FILE_LOAD_ERROR';
export const FILE_DELETE='FILE_DELETE';
export const FILE_DELETE_SUCCESS='FILE_DELETE_SUCCESS';
export const FILE_DELETE_ERROR='FILE_DELETE_ERROR';

