export const FILE_UPLOAD='FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS='FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR='FILE_UPLOAD_ERROR';
export const FILE_LOAD='FILE_LOAD';
export const FILE_LOAD_SUCCESS='FILE_LOAD_SUCCESS';
export const FILE_LOAD_ERROR='FILE_LOAD_ERROR';
export const FILE_DELETE='FILE_DELETE';
export const FILE_DELETE_SUCCESS='FILE_DELETE_SUCCESS';
export const FILE_DELETE_ERROR='FILE_DELETE_ERROR';
export const FILE_RENAME='FILE_RENAME';
export const FILE_RENAME_SUCCESS='FILE_RENAME_SUCCESS';
export const FILE_RENAME_ERROR='FILE_RENAME_ERROR';
export const FILE_DOWNLOAD='FILE_DOWNLOAD';
export const FILE_DOWNLOAD_SUCCESS='FILE_DOWNLOAD_SUCCESS';
export const FILE_DOWNLOAD_ERROR='FILE_DOWNLOAD_ERROR';



