name: FastApi Deploy

on:
  push:
    branches:
      - "main"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Repo
     uses: actions/checkout@v1

   - name: Update Code
     run: |
      git config user.email "sachinsom@github.com"
      git config user.name "sachin som"
      git add -A && git commit -m "Update Code!"

   - name: Deploying to Heroku
     uses: akhileshns/heroku-deploy@v3.12.12
     with:
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      heroku_app_name: "blob-storage-server"
      heroku_email: "sachinsom507@gmail.com"
