name: Heroku Deploy

on:
  push:
    branches:
      - "master"

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
    matrix:
     node-version: [15.x]

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Install and Build
      run: |
       cd frontend
       npm install
       npm run build
       cd ..
       
    - name: Update the latest git commit
      run: |
       git config user.email "sachinsom507@github.com"
       git config user.name "Sachin Som"
       git add -A && git commit -m "Updated Code!"
 
    - name: Deploy React App 🚀
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
       heroku_app_name: "blob-storage"
       heroku_email: "sachinsom507@gmail.com"
       appdir: "frontend/build"
   

    - name: Display Success Message
      run: echo "React App Deployed 🎉"
